config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, skip: [:sessions, :registrations], controllers: {passwords: "passwords"}
  as :user do
    get "signin", to: "sessions#new", as: :new_user_session
    post "signin", to: "devise/sessions#create", as: :user_session
    delete "signout", to: "devise/sessions#destroy", as: :destroy_user_session
    get "signup", to: "registrations#new", as: :new_user_registration
    get "my_account/account_details", to: "devise/registrations#edit", as: :edit_user_registration
    post "users", to: "devise/registrations#create", as: :user_registration
    patch "users", to: "devise/registrations#update"
    put "users", to: "devise/registrations#update"
    get "my_account/account_details", to: "devise/registrations#edit", as: :user_root
  end

  get "/contact_us", to: "pages#contact"
  get "/privacy_policy", to: "pages#privacy"
  get "/rules", to: "pages#rules"
  get "/terms_of_use", to: "pages#terms", as: :terms
  get "/my_account/deposit", to: "account#deposit"
  post "/my_account/deposit", to: "account#charge_card"
  #post "my_account/balance", to: "account#paypal", as: :paypal
  match "/my_account/withdraw", to: "account#withdraw", via: [:get, :post]
  match "/my_account/transfer", to: "account#transfer", via: [:get, :post]
  get "/my_account/balance", to: "account#balance"
  get "/my_account/challenge", to: "account#challenge"
  get "/my_account/bonuses", to: "account#bonuses"
  get "my_account/affiliate", to: "account#affiliate"
  get "/my_fantasy/my_action", to: "fantasy#my_action"
  get "/my_fantasy/my_history", to: "fantasy#my_history"
  get "/my_fantasy/my_stats", to: "fantasy#my_stats"
  get "/my_fantasy/leaderboard", to: "fantasy#leaderboard"
  resources :props
  post "wagers", to: "wagers#create", as: :wagers
  get "pc", to: "props#pc"
  get "prop", to: "props#prop"
  get "bc", to: "account#bc"
  get "balance", to: "application#balance"
  post "/notifications/notify", to: "twilio#notify"

  root to: "props#index"
end

app/models/prop.rb
# == Schema Information
#
# Table name: props
#
#  id             :integer          not null, primary key
#  sport_id       :integer
#  time           :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  state          :integer          default("0")
#  proposition    :text(65535)
#  opt1_spread    :float(24)
#  opt2_spread    :float(24)
#  winner         :integer
#  user_id        :integer
#  delayed_job_id :integer
#  tv             :string(255)      default("")
#
# Indexes
#
#  index_props_on_sport_id  (sport_id)
#  index_props_on_user_id   (user_id)
#

class Prop < ActiveRecord::Base
  include AASM, StorageConversions

  belongs_to :sport
  belongs_to :user
  has_many :wagers, dependent: :restrict_with_error
  has_many :prop_choices
  accepts_nested_attributes_for :prop_choices, allow_destroy: true

  validates :sport_id, presence: true
  validates :time, presence: true
  validates :opt1_spread, presence: true

  just_define_datetime_picker :time
  display_line :opt1_spread
  display_line :opt2_spread

  enum state: [ :Offline, :Open, :Closed, :Graded, :Regrade ]
  enum winner: [ :Team1, :Team2, :Push, :NoAction]

  after_initialize :set_time, :set_opt1_spread
  before_save :check_state
  before_validation :get_opt2_spread
  after_save :close_wagering, if: Proc.new {|a| a.time_changed?}
  after_save :get_dj_id, if: Proc.new {|a| a.time_changed?}
  #after_touch :auto_move_odds
  attr_accessor :ampm_time

  def set_time
    self.time ||= Time.now
  end

  def set_opt1_spread
    self.opt1_spread ||= 0
  end

  def ampm_time
    self.time.strftime("%I:%M %P")
  end

  def self.search(search_string)
    players = Player.where('name LIKE ? or team LIKE ?', "%#{search_string}%", "%#{search_string}%")
    prop_collection = []
    props = []
    all_prop_choices = PropChoice.joins(:prop).where('props.state' => 1)
    players.each do |player|
      all_prop_choices.each do |pc|
        if pc.choice.include? player.id
          prop_collection << pc.prop.id
        end
      end
    end
    #choice_collection.flatten.each do |choice|
     # props << choice.prop_id if choice.prop.state == "Open"
    #end
    self.where("id in (?)", prop_collection)
  end

  def check_state
    if self.state == "Closed" && has_winner?
      self.grade_prop!
      wagers = Wager.where(prop_id: self.id)
      wagers.each do |wager|
        if wager.user.email_notif?
          MailgunMailer.contest_graded(wager).deliver_later
        end
        #if wager.user.sms_notif?
         # Text.contest_graded(wager)
        #end
      end
    elsif self.state == "Regrade"
      self.ungrade_wagers
      self.state = "Closed"
      self.grade_prop!
      wagers = Wager.where(prop_id: self.id)
      wagers.each do |wager|
        if wager.user.email_notif?
          MailgunMailer.contest_graded(wager).deliver_later
        end
        #if wager.user.sms_notif?
         # Text.contest_graded(wager)
        #end
      end
    end
  end

  def get_opt2_spread
    if self.opt1_spread == 0 || self.opt1_spread.blank?
      self.opt2_spread = 0
    else
      self.opt2_spread = self.opt1_spread * -1.0
    end
  end

  def exposure
    win_array = []
    risk_array = []
    choice_array = []
    risk_counter = 0
    self.prop_choices.each do |choice|
      win_array << choice.choice_win
      risk_array << choice.choice_risk
      choice_array << choice.id
    end
    win = win_array.max
    place = win_array.index(win_array.max)
    risk_array.delete_at(place)
    risk_array.each do |element|
      risk_counter += element
    end
    (choice_array[place]).to_s + " " + ((win - risk_counter).round(2)).to_s
  end

  def exposure_to_s
    name = PropChoice.find_by(id: self.exposure.split[0]).name
    name + "  (" + self.exposure.split[1] + ")"
  end

  def auto_move_odds
    exposure = self.exposure.split[1].to_i
    id = self.exposure.split[0].to_i
    newLine = exposure / 2500 * -10 + -115
    newLine2 = exposure / 2500 * 10 + -115
    if newLine2 > -100
      newLine2 = newLine2 +=200
    end
    choice = PropChoice.find_by(id: id)
    choice.odds = newLine
    choice.save
    if self.prop_choices.first == choice
      self.prop_choices.last.odds = newLine2
      self.prop_choices.last.save
    else
      self.prop_choices.first.odds = newLine2
      self.prop_choices.first.save
    end
  end

  def has_winner?
    self.winner != nil
  end

  def get_dj_id
    if self.delayed_job_id
      if Delayed::Job.where(id: self.delayed_job_id).exists?
        Delayed::Job.find(self.delayed_job_id).destroy
      end
    end
    self.delayed_job_id = Delayed::Job.where(queue: "CloseWagering").last.id
    self.save
  end

  handle_asynchronously :get_dj_id, queue: "Get_DJ_ID", :run_at => Proc.new { 5.seconds.from_now }

  def close_wagering
    if self.state == "Offline" || self.state == "Open"
      self.state = "Closed"
      self.save
    end
    wagers = Wager.where(prop_id: self.id)
    wagers.each do |wager|
      if wager.user.email_notif?
        MailgunMailer.contest_started(wager).deliver_later
      end
      #if wager.user.sms_notif?
       # Text.contest_started(wager)
      #end
    end
  end

  handle_asynchronously :close_wagering, queue: "CloseWagering", :run_at => Proc.new { |i| i.time }

  aasm column: :state do
    state :Offline, initial: true

    event :allow_wagering do
      transitions from: :Offline, to: :Open
    end

    state :Open

    event :close_prop do
      transitions from: :Open, to: :Closed
    end

    event :pause_prop do
      transitions from: :Open, to: :Offline
    end

    state :Closed

    event :grade_prop do
      transitions from: :Closed, to: :Graded
    end

    state :Graded, after_commit: :grade_wagers

    event :regrade_prop do
      transitions from: :Graded, to: :Regrade
    end

    state :Regrade
  end

  def grade_wagers
    wagers = Wager.where(prop_id: self.id)
    choice1 = PropChoice.where(prop_id: self.id).first
    choice2 = PropChoice.where(prop_id: self.id).last
    wagers.map do |wager|
      if wager.prop_choice == choice1
        if wager.prop.winner == "Team1"
          wager.win_wager!
        elsif wager.prop.winner == "Team2"
          wager.lose_wager!
        elsif wager.prop.winner == "Push"
          wager.push_wager!
        else
          wager.void_wager!
        end
      else
        if wager.prop.winner == "Team2"
          wager.win_wager!
        elsif wager.prop.winner == "Team1"
          wager.lose_wager!
        elsif wager.prop.winner == "Push"
          wager.push_wager!
        else
          wager.void_wager!
        end
      end
    end
  end

  def ungrade_wagers
    wagers = Wager.where(prop_id: self.id)
    wagers.map do |wager|
      wager.ungrade_wager
    end
  end

  def display_proposition
    if self.proposition == "Vs."
      self.prop_choices.first.name + " Vs. " + self.prop_choices.last.name
    else
      self.proposition
    end
  end

end

app/controllers/props_controller.rb
class PropsController < ApplicationController
  layout "prop"

  def index
    if params[:q].present?
      @props = Prop.search(params[:q]).order('time')
    elsif params[:sport_id].present?
      @props = Prop.where(sport_id: params[:sport_id], state: 1).order('time')
    else
      @props = Prop.where(state: 1).order('time')
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @prop = Prop.find(params[:id])
    respond_to do |format|
      if @prop.update_attributes(prop_params)
        format.js { render nothing: true }
      end
    end
  end

  def pc
    respond_to do |format|
      format.json do
        prop_choice_id = params[:prop_choice_id]
        @prop_choice = PropChoice.find_by id: prop_choice_id
        render json: @prop_choice.to_json(:include => [:prop], :methods => [:display_line, :display_spread, :name, :available_dollars, :display_proposition])
      end
    end
  end

  def prop
    respond_to do |format|
      format.json do
        prop_id = params[:prop_id]
        @prop = Prop.find_by id: prop_id
        render json: @prop.to_json(:include => [:prop_choices])
      end
    end
  end

  private

  def prop_params
    params.require(:prop).permit(:winner, :state)
  end

end

app/views/props/_proplist.html.erb
        <% @props.each do |prop| %>
            <div class="col-md-7 matchups">

            <div class="col-md-3 matchup-left choice open"><div class="side open-side">Matchup Side Open</div>
              <div class="info open-info">
                <div class="contenders" data-propchoiceid="<%= prop.prop_choices.first.id %>"><%= prop.prop_choices.first.name %> <div class="odd-line"> <%= prop.prop_choices.first.display_spread %> </div> </div>
                <div class="enter-contest">
                <div class="available-cost available-odd">
                Min: $5.00 <br/> Max: <%= number_to_currency prop.prop_choices.first.available_dollars %> </div><button name="button" type="button" class="enter-button first" data-propchoiceid="<%= prop.prop_choices.first.id %>">Enter Contest</button></div>
              </div>
            </div>

            <div class="col-md-1 matchup-info"><p> <%= prop.sport.name %> </p><%= prop.time.strftime("%B %-d, %Y %n %l:%M %P EST") %>
              <div class="vs">Vs</div>
              <div class="prop-timer" data-time="<%= prop.time.to_i * 1000  %>"> </div>
              <div class="tv"> <%= prop.tv %> </div>
            </div>

            <div class="col-md-3 matchup-right choice open"><div class="side open-side">Matchup Side Open</div>
            <div class="info open-info">
            <div class="contenders" data-propchoiceid="<%= prop.prop_choices.last.id %>"> <%= prop.prop_choices.last.name %> <div class="even-line"> <%= prop.prop_choices.last.display_spread %> </div> </div>
            <div class="enter-contest">
            <div class="available-cost available-even"> Min: $5.00 <br/> Max: <%= number_to_currency prop.prop_choices.last.available_dollars %> </div><button name="button" type="button" class="enter-button last" data-propchoiceid="<%= prop.prop_choices.last.id %>" >Enter Contest</button></div>
            </div>
            </div>
            </div>
        <% end %>

<script type='text/javascript'>
  $(document).ready(function(){

    var odds = $('.matchups').find('.available-odd'), i;
    for (var i = 0; i < odds.length; i ++) {
      if ($(odds[i]).text().trim() == "Min: $5.00  Max: $0.00") {
        $(odds[i]).css("visibility", "hidden");
        choice = $(odds[i]).closest('.choice')
        side = $(choice).find(".open-side")
        info = $(choice).find(".open-info")
        btn = $(choice).find(".enter-button")
        $(side).text("Matchup Side Closed")
        $(side).removeClass("open-side")
        $(side).addClass("closed-side")
        $(choice).removeClass("open")
        $(choice).addClass("closed")
        $(info).removeClass("open-info")
        $(info).addClass("closed-info")
        $(btn).prop('disabled', true)
      }
    }

    var evens = $('.matchups').find('.available-even'), i;
    for (var i = 0; i < odds.length; i ++) {
      if ($(evens[i]).text().trim() == "Min: $5.00  Max: $0.00") {
        $(evens[i]).css("visibility", "hidden");
        choice = $(evens[i]).closest('.choice')
        side = $(choice).find(".open-side")
        info = $(choice).find(".open-info")
        btn = $(choice).find(".enter-button")
        $(side).text("Matchup Side Closed")
        $(side).removeClass("open-side")
        $(side).addClass("closed-side")
        $(choice).removeClass("open")
        $(choice).addClass("closed")
        $(info).removeClass("open-info")
        $(info).addClass("closed-info")
        $(btn).prop('disabled', true)
      }
    }

    setInterval(function () {
      var countdowns = $('.matchups').find('.prop-timer'), i;
      for (var i = 0; i < countdowns.length; i ++) {
        var target_date = $(countdowns[i]).data('time')
        var hours, minutes, seconds;
        var current_date = new Date().getTime();
        var seconds_left = (target_date - current_date) / 1000 + 20;  //20 sec diff between heroku time and Javascript time.
        hours = parseInt(seconds_left / 3600);
        seconds_left = seconds_left % 3600;
        minutes = parseInt(seconds_left / 60);
        seconds = parseInt(seconds_left % 60);
        if (hours.toString().length == 1) {
          hours = "0" + hours;
        }
        if (minutes.toString().length == 1) {
          minutes = "0" + minutes;
        }
        if (seconds.toString().length == 1) {
          seconds = "0" + seconds;
        }
        if (hours <= 0 && minutes <= 0 && seconds <= 0 ) {
          $(countdowns[i]).text("Event has started.");
        } else {
          $(countdowns[i]).text("Starts In " + hours + ":" + minutes + ":" + seconds);
        }
      }
    }, 1000);

    setInterval(function () {
      var wagers = $('.matchups').find('.enter-button');
      $.each(wagers, function(index, value) {
        $.ajax({
          url: "/pc",
          type: "GET",
          data: {prop_choice_id: $(value).data('propchoiceid')},
          success: function (data) {
            updateAvailable(data, value);
          },
          error: function (xhr, status, error) {
            console.log(status + error);
          }
        });
      });
    }, 10000);

    function updateAvailable (responseData, value) {
          available = responseData.available_dollars;
          display_spread = responseData.display_spread;
          if (value.classList.contains("first")) {
            container = value.closest(".choice")
            var odd = $(container).find('.available-odd')
            var side = $(container).find('.side')
            var info = $(container).find('.info')
            if (available == 0) {
              $(odd).css("visibility", "hidden");
              $(side).text("Matchup Side Closed")
              $(side).removeClass("open-side")
              $(side).addClass("closed-side")
              $(container).removeClass("open")
              $(container).addClass("closed")
              $(info).removeClass("open-info")
              $(info).addClass("closed-info")
              $(value).prop('disabled', true)
            } else {
              $(odd).html("Min: $5.00 <br/> Max: $" + available.toFixed(2))
              $(odd).css("visibility", "visible");
              $(side).text("Matchup Side Open")
              $(side).addClass("open-side")
              $(side).removeClass("closed-side")
              $(container).addClass("open")
              $(container).removeClass("closed")
              $(info).addClass("open-info")
              $(info).removeClass("closed-info")
              $(value).prop('disabled', false);
            }
          } else {
            container = value.closest(".choice")
            var even = $(container).find('.available-even')
            var side = $(container).find('.side')
            var info = $(container).find('.info')
            if (available == 0) {
              $(even).css("visibility", "hidden");
              $(side).text("Matchup Side Closed")
              $(side).removeClass("open-side")
              $(side).addClass("closed-side")
              $(container).removeClass("open")
              $(container).addClass("closed")
              $(info).removeClass("open-info")
              $(info).addClass("closed-info")
              $(value).prop('disabled', true);
            } else {
              $(even).html("Min: $5.00 <br/> Max: $" + available.toFixed(2))
              $(even).css("visibility", "visible");
              $(side).text("Matchup Side Open")
              $(side).addClass("open-side")
              $(side).removeClass("closed-side")
              $(container).addClass("open")
              $(container).removeClass("closed")
              $(info).addClass("open-info")
              $(info).removeClass("closed-info")
              $(value).prop('disabled', false);
            }
          }
    }
  })
</script>

app/views/props/index.html.erb
<div class="row main-content">

  <div class ="col-md-2 prop-sports">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "live_draft.jpg", title: "Live-Draft", alt: "Live-Draft" %>
    </div>

    <div class="item">
      <%= image_tag "sportsticker.jpg", title: "Sportsticker", alt: "Sportsticker" %>
    </div>

    <div class="item">
      <%= image_tag "Matchup-Contests.png", title: "Matchup-Contests", alt: "Matchup-Contests" %>
    </div>

  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  </div>

  <div class="col-md-7 wrapper">
    <div class="col-lg-7 note">
    <div class="row">
    <div class=" col-lg-7 notice-disclaimer"><div class="notice-area">Notice: All matchup contests are offered by customers. </div>

    <%= form_tag props_path, id: "search", method: :get, remote: true do %>
      <%= text_field_tag :q, "", placeholder: "Search by team or player" %>
      <%= submit_tag "Search" %>
    <% end %>
      </div>
    </div>
  </div>
    <div id="props">
      <%= render "proplist" %>
    </div>
  </div>

  <div class ="col-md-3 ticket">
    <h5> Fantasy Ticket </h5>
      <div class="alert hidden">
      </div>

    <%= form_tag wagers_path, method: :post, remote: true do %>
      <table>

        <tbody class="actions hidden">
        <tr>
          <td colspan="6"> <%= password_field_tag 'password', nil, placeholder: "password to confirm" %> </td>
          <td> <%= submit_tag "Submit", class: "wager-submit", data: { disable_with: "Submitted" } %> </td>
        </tr>
        </tbody>

        <tbody class="new-wager-row wager hidden">
        <tr>
          <td colspan="6"> <p type="text" class="success hidden"></p></td>
        </tr>
        <tr>
          <td colspan="6"> <p type="text" class="failure hidden"></p></td>
        </tr>
        <tr>
          <td colspan="6"> <p type="text" class="wager-info"></p> </td>
          <td> <%= button_tag "", type: "button", class: "delete-wager glyphicon glyphicon-remove" %> </td>
        </tr>
        <tr>
          <td id="risk"> <strong> Buy In </strong> <%= text_field_tag "wager[][risk_dollars]", nil, class: "wager-risk", value: number_with_precision(0.00, precision: 2) %> </td>
          <td id="win"> <strong> Win </strong> <input type="text" class="wager-win" value="0.00"> </td>
          <td> <%= text_field_tag "wager[][prop_id]", nil, class: "wager-prop-id hidden", readonly: "readonly" %> </td>
          <td> <%= text_field_tag "wager[][prop_choice_id]", nil, class: "wager-prop-choice-id hidden", readonly: "readonly" %> </td>
          <td> <%= text_field_tag "wager[][odds]", nil, class: "wager-odds hidden", readonly: "readonly" %> </td>
          <td> <%= text_field_tag "wager[][spread]", nil, class: "wager-spread hidden", readonly: "readonly" %> </td>
        </tr>
        </tbody>

      </table>
    <% end %>
  </div>
</div>

app/views/props/index.js.erb
var newHtml = "<%= escape_javascript(render 'proplist') %>";


$("#props").html(newHtml);