config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, skip: [:sessions, :registrations], controllers: {passwords: "passwords"}
  as :user do
    get "signin", to: "sessions#new", as: :new_user_session
    post "signin", to: "devise/sessions#create", as: :user_session
    delete "signout", to: "devise/sessions#destroy", as: :destroy_user_session
    get "signup", to: "registrations#new", as: :new_user_registration
    get "my_account/account_details", to: "devise/registrations#edit", as: :edit_user_registration
    post "users", to: "devise/registrations#create", as: :user_registration
    patch "users", to: "devise/registrations#update"
    put "users", to: "devise/registrations#update"
    get "my_account/account_details", to: "devise/registrations#edit", as: :user_root
  end

  get "/contact_us", to: "pages#contact"
  get "/privacy_policy", to: "pages#privacy"
  get "/rules", to: "pages#rules"
  get "/terms_of_use", to: "pages#terms", as: :terms
  get "/my_account/deposit", to: "account#deposit"
  post "/my_account/deposit", to: "account#charge_card"
  #post "my_account/balance", to: "account#paypal", as: :paypal
  match "/my_account/withdraw", to: "account#withdraw", via: [:get, :post]
  match "/my_account/transfer", to: "account#transfer", via: [:get, :post]
  get "/my_account/balance", to: "account#balance"
  get "/my_account/challenge", to: "account#challenge"
  get "/my_account/bonuses", to: "account#bonuses"
  get "my_account/affiliate", to: "account#affiliate"
  get "/my_fantasy/my_action", to: "fantasy#my_action"
  get "/my_fantasy/my_history", to: "fantasy#my_history"
  get "/my_fantasy/my_stats", to: "fantasy#my_stats"
  get "/my_fantasy/leaderboard", to: "fantasy#leaderboard"
  resources :props
  post "wagers", to: "wagers#create", as: :wagers
  get "pc", to: "props#pc"
  get "prop", to: "props#prop"
  get "bc", to: "account#bc"
  get "balance", to: "application#balance"
  post "/notifications/notify", to: "twilio#notify"

  root to: "props#index"
end

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<head>
  <title>FantasyBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path do %>
          <%= image_tag "fb-guru-logo.png", title: "FantasyBook Logo", class: "fbg-logo", alt: "FantasyBook.guru" %>
        <% end %>
        <div class="social">
        <div class="facebook">
        <%= link_to "https://www.facebook.com/pages/Fantasybookguru/1503513283269643" do %>
          <%=image_tag "facebook.png", alt: "facebook" %>
        <% end %>
        </div>
        <div class="twitter">
          <%= link_to "https://twitter.com/fantasybooklive" do %>
            <%=image_tag "twitter.png", alt: "twitter" %>
          <% end %>
        </div>
        </div>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="welcome"> Welcome, <%= current_user.username %> </li>
          <li> <%= link_to "My Fantasy", my_fantasy_my_action_path %> </li>
          <li> <%= link_to "My Account", my_account_balance_path %> </li>
          <li> <%= link_to "Deposit", my_account_deposit_path %> </li>
          <li id="balance_header"> <%= link_to my_account_balance_path do %>
               Balance: <%= number_to_currency current_user.balance_dollars %>
              <% end %>
          </li>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Sign In", new_user_session_path %> </li>
          <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
        <% end %>

          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Contact<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <li> <%= link_to "Contact Us", contact_us_path %> </li>
          <li> <%= link_to "Rules", rules_path %> </li>
          <li> <%= link_to "Privacy Policy", privacy_policy_path %> </li>
          <li> <%= link_to "Terms of Use", terms_path %> </li>
        </ul>

      </div>
    </div>
  </nav>

  <nav class="navbar navbar-default navbar-inverse navbar-fixed-bottom" role="navigation">
    <div class="container footer">
    <div class="row">
      <div class="border col-md-12 ">
          <div class="row-fluid">
    <div class="carousel slide" id="team-games">
        <div class="carousel-inner fantasynews">
          <div class="item active">
                <ul class="game-thumbnails">
                        <div class="game-thumbnail">
                            <span class="team">Player News & Injury Reports coming here soon</span>
                        </div>
                </ul>
          </div>
          <div class="item">
                <ul class="game-thumbnails">
                        <div class="game-thumbnail">
                            <span class="team"> <a href="https://www.facebook.com/pages/Fantasybookguru/1503513283269643">Check us out on Facebook</a>
                              <%= link_to "https://www.facebook.com/pages/Fantasybookguru/1503513283269643" do %>
                                <%= image_tag "facebook.jpeg", size: "15x15", title: "Facebook Logo", alt: "Facebook" %>
                              <% end %></span>
                        </div>
                </ul>
          </div>
        </div>
        <a data-slide="prev" href="#team-games" class="left carousel-control teams">‹</a>
        <a data-slide="next" href="#team-games" class="right carousel-control teams">›</a>
    </div>
</div>
   </div>
    </div>

      <div class="navbar-left">
        <p class="navbar-text">
          <%= link_to "Contact Us", contact_us_path %> |
          <%= link_to "Rules", rules_path %> |
          <%= link_to "Privacy Policy", privacy_policy_path %> |
          <%= link_to "Terms of Use", terms_path %> |
          <%= link_to "Blog", "http://blog.fantasybook.guru" %>
        </p>
      </div>
  </nav>

<div class="contest row">
  <div class="border col-xs-3 fb-top-nav">
    <%= link_to root_path do %>
      <%= image_tag "matchup-icon.png", class: "contest-icon" %>
      Matchup Contests
    <% end %>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true"><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> <%= link_to "All", root_path %> </li>
            <% @sport_filters.each do |sport|  %>
              <% if sport.has_active_matchups? %>
                <li> <%= link_to sport.name, {controller: "/props", action: "index", sport_id: sport.id}, method: :get %> </li>
              <% end %>
            <% end %>
          </ul>
      </li>
  </div>
  <div class="border col-xs-3 group">
    <%= image_tag "live-draft-icon.png", class: "contest-icon" %>Live Draft - coming soon </div>
  <div class="border col-xs-3 group">
  <%= image_tag "multi-entry-icon.png", class: "contest-icon" %> Multi-Entry - coming soon</div>
  <div class="border col-xs-3 group">
  <%= image_tag "survivor-icon.png", class: "contest-icon" %> Survivor Contests - coming soon </div>
</div>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <ul class="nav nav-tabs">
        <li role="presentation" class="<%= 'active' if current_page?(edit_user_registration_path) %>"> <%= link_to "Account Details", edit_user_registration_path %></li>
        <li role="presentation" class="<%= 'active' if current_page?(my_account_deposit_path) %>"> <%= link_to "Deposit", my_account_deposit_path %></li>
        <li role="presentation" class="<%= 'active' if current_page?(my_account_withdraw_path) %>"> <%= link_to "Withdraw", my_account_withdraw_path %></li>
        <li role="presentation" class="<%= 'active' if current_page?(my_account_transfer_path) %>"> <%= link_to "Transfer", my_account_transfer_path %></li>
        <li role="presentation" class="<%= 'active' if current_page?(my_account_bonuses_path) %>"> <%= link_to "Bonuses", my_account_bonuses_path %></li>
        <% if current_user.affiliate? %>
          <li role="presentation" class="<%= 'active' if current_page?(my_account_affiliate_path) %>"> <%= link_to "Affiliate", my_account_affiliate_path %></li>
        <% end %>
        <li role="presentation" class="<%= 'active' if current_page?(my_account_balance_path) %>"> <%= link_to "Balance", my_account_balance_path %></li>
      </ul>
    </div>
  </nav>

  <% if flash[:alert] %>
    <div class="alert">
      <%= alert %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<head>
  <title>FantasyBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path do %>
          <%= image_tag "fb-guru-logo.png", title: "FantasyBook Logo", class: "fbg-logo", alt: "FantasyBook.guru" %>
        <% end %>
        <div class="social">
        <div class="facebook">
        <%= link_to "https://www.facebook.com/pages/Fantasybookguru/1503513283269643" do %>
          <%=image_tag "facebook.png", alt: "facebook" %>
        <% end %>
        </div>
        <div class="twitter">
          <%= link_to "https://twitter.com/fantasybooklive" do %>
            <%=image_tag "twitter.png", alt: "twitter" %>
          <% end %>
        </div>
        </div>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="welcome"> Welcome, <%= current_user.username %> </li>
          <li> <%= link_to "My Fantasy", my_fantasy_my_action_path %> </li>
          <li> <%= link_to "My Account", my_account_balance_path %> </li>
          <li> <%= link_to "Deposit", my_account_deposit_path %> </li>
          <li id="balance_header"> <%= link_to my_account_balance_path do %>
               Balance: <%= number_to_currency current_user.balance_dollars %>
              <% end %> </li>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Sign In", new_user_session_path %> </li>
          <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
        <% end %>

          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Contact<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <li> <%= link_to "Contact Us", contact_us_path %> </li>
          <li> <%= link_to "Rules", rules_path %> </li>
          <li> <%= link_to "Privacy Policy", privacy_policy_path %> </li>
          <li> <%= link_to "Terms of Use", terms_path %> </li>
        </ul>

      </div>
    </div>
  </nav>

  <nav class="navbar navbar-default navbar-inverse navbar-fixed-bottom" role="navigation">
    <div class="container footer">
    <div class="row">
      <div class="border col-md-12 ">
          <div class="row-fluid">
    <div class="carousel slide" id="team-games">
        <div class="carousel-inner fantasynews">
          <div class="item active">
                <ul class="game-thumbnails">
                        <div class="game-thumbnail">
                            <span class="team">Player News & Injury Reports coming here soon</span>
                        </div>
                </ul>
          </div>
          <div class="item">
                <ul class="game-thumbnails">
                        <div class="game-thumbnail">
                            <span class="team"> <a href="https://www.facebook.com/pages/Fantasybookguru/1503513283269643">Check us out on Facebook</a>
                              <%= link_to "https://www.facebook.com/pages/Fantasybookguru/1503513283269643" do %>
                                <%= image_tag "facebook.jpeg", size: "15x15", title: "Facebook Logo", alt: "Facebook" %>
                              <% end %></span>
                        </div>
                </ul>
          </div>
        </div>
        <a data-slide="prev" href="#team-games" class="left carousel-control teams">‹</a>
        <a data-slide="next" href="#team-games" class="right carousel-control teams">›</a>
    </div>
</div>
   </div>
    </div>

      <div class="navbar-left">
        <p class="navbar-text">
          <%= link_to "Contact Us", contact_us_path %> |
          <%= link_to "Rules", rules_path %> |
          <%= link_to "Privacy Policy", privacy_policy_path %> |
          <%= link_to "Terms of Use", terms_path %> |
          <%= link_to "Blog", "http://blog.fantasybook.guru" %>
        </p>
      </div>
  </nav>

<div class="contest row">
  <div class="border col-xs-3 fb-top-nav">
    <%= link_to root_path do %>
      <%= image_tag "matchup-icon.png", class: "contest-icon" %>
      Matchup Contests
    <% end %>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true"><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> <%= link_to "All", root_path %> </li>
            <% @sport_filters.each do |sport|  %>
              <% if sport.has_active_matchups? %>
                <li> <%= link_to sport.name, {controller: "/props", action: "index", sport_id: sport.id}, method: :get %> </li>
              <% end %>
            <% end %>
          </ul>
      </li>
  </div>
  <div class="border col-xs-3 group">
    <%= image_tag "live-draft-icon.png", class: "contest-icon" %>Live Draft - coming soon </div>
  <div class="border col-xs-3 group">
  <%= image_tag "multi-entry-icon.png", class: "contest-icon" %> Multi-Entry - coming soon</div>
  <div class="border col-xs-3 group">
  <%= image_tag "survivor-icon.png", class: "contest-icon" %> Survivor Contests - coming soon </div>
</div>

  <% if flash[:alert] %>
    <div class="alert">
      <%= alert %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/layouts/fantasy.html.erb
<!DOCTYPE html>
<html>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<head>
  <title>FantasyBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path do %>
          <%= image_tag "fb-guru-logo.png", title: "FantasyBook Logo", class: "fbg-logo", alt: "FantasyBook.guru" %>
        <% end %>
        <div class="social">
        <div class="facebook">
        <%= link_to "https://www.facebook.com/pages/Fantasybookguru/1503513283269643" do %>
          <%=image_tag "facebook.png", alt: "facebook" %>
        <% end %>
        </div>
        <div class="twitter">
          <%= link_to "https://twitter.com/fantasybooklive" do %>
            <%=image_tag "twitter.png", alt: "twitter" %>
          <% end %>
        </div>
        </div>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="welcome"> Welcome, <%= current_user.username %> </li>
          <li> <%= link_to "My Fantasy", my_fantasy_my_action_path %> </li>
          <li> <%= link_to "My Account", my_account_balance_path %> </li>
          <li> <%= link_to "Deposit", my_account_deposit_path %> </li>
          <li id="balance_header"> <%= link_to my_account_balance_path do %>
               Balance: <%= number_to_currency current_user.balance_dollars %>
              <% end %> </li>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Sign In", new_user_session_path %> </li>
          <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
        <% end %>

          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Contact<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <li> <%= link_to "Contact Us", contact_us_path %> </li>
          <li> <%= link_to "Rules", rules_path %> </li>
          <li> <%= link_to "Privacy Policy", privacy_policy_path %> </li>
          <li> <%= link_to "Terms of Use", terms_path %> </li>
        </ul>

      </div>
    </div>
  </nav>

  <nav class="navbar navbar-default navbar-inverse navbar-fixed-bottom" role="navigation">
    <div class="container footer">
    <div class="row">
      <div class="border col-md-12 ">
          <div class="row-fluid">
    <div class="carousel slide" id="team-games">
        <div class="carousel-inner fantasynews">
          <div class="item active">
                <ul class="game-thumbnails">
                        <div class="game-thumbnail">
                            <span class="team">Player News & Injury Reports coming here soon</span>
                        </div>
                </ul>
          </div>
          <div class="item">
                <ul class="game-thumbnails">
                        <div class="game-thumbnail">
                            <span class="team"> <a href="https://www.facebook.com/pages/Fantasybookguru/1503513283269643">Check us out on Facebook</a>
                              <%= link_to "https://www.facebook.com/pages/Fantasybookguru/1503513283269643" do %>
                                <%= image_tag "facebook.jpeg", size: "15x15", title: "Facebook Logo", alt: "Facebook" %>
                              <% end %></span>
                        </div>
                </ul>
          </div>
        </div>
        <a data-slide="prev" href="#team-games" class="left carousel-control teams">‹</a>
        <a data-slide="next" href="#team-games" class="right carousel-control teams">›</a>
    </div>
</div>
   </div>
    </div>

      <div class="navbar-left">
        <p class="navbar-text">
          <%= link_to "Contact Us", contact_us_path %> |
          <%= link_to "Rules", rules_path %> |
          <%= link_to "Privacy Policy", privacy_policy_path %> |
          <%= link_to "Terms of Use", terms_path %> |
          <%= link_to "Blog", "http://blog.fantasybook.guru" %>
        </p>
      </div>
  </nav>

<div class="contest row">
  <div class="border col-xs-3 fb-top-nav">
    <%= link_to root_path do %>
      <%= image_tag "matchup-icon.png", class: "contest-icon" %>
      Matchup Contests
    <% end %>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true"><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> <%= link_to "All", root_path %> </li>
            <% @sport_filters.each do |sport|  %>
              <% if sport.has_active_matchups? %>
                <li> <%= link_to sport.name, {controller: "/props", action: "index", sport_id: sport.id}, method: :get %> </li>
              <% end %>
            <% end %>
          </ul>
      </li>
  </div>
  <div class="border col-xs-3 group">
    <%= image_tag "live-draft-icon.png", class: "contest-icon" %>Live Draft - coming soon </div>
  <div class="border col-xs-3 group">
  <%= image_tag "multi-entry-icon.png", class: "contest-icon" %> Multi-Entry - coming soon</div>
  <div class="border col-xs-3 group">
  <%= image_tag "survivor-icon.png", class: "contest-icon" %> Survivor Contests - coming soon </div>
</div>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <ul class="nav nav-tabs">
        <li role="presentation" class="<%= 'active' if current_page?(my_fantasy_my_action_path) %>"> <%= link_to "My Action", my_fantasy_my_action_path %></li>
        <li role="presentation" class="<%= 'active' if current_page?(my_fantasy_my_history_path) %>"> <%= link_to "My History", my_fantasy_my_history_path %></li>
      </ul>
    </div>
  </nav>

  <% if flash[:alert] %>
    <div class="alert">
      <%= alert %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>